[package]
name = "helixcoin"
version = "0.1.0"
edition = "2018"

[dependencies]
solana-program = "1.10.0"
spl-token = "4.0.1"
arrayref = "0.3"
borsh = "0.9.1"
thiserror = "1.0"
log = "0.4"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []